version: '3'
services:
  database:
    image: mysql:5.7
    container_name: 'some_mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - 3306:3306
    volumes:
      - 'dbdata:/var/lib/mysql'
volumes:
  dbdata:
